### ISSUE TITLE
Only emit B019 when `maxsize` is `None` in `lru_cache`?

### ISSUE THREAD

**Issue by lafrech** [PyCQA/flake8-bugbear#310] opened 2022-11-15 10:32 UTC
Shouldn't B019 be emitted only when `maxsize` is `None`, as in https://github.com/PyCQA/pylint/pull/6181?

**Comment by JelleZijlstra** [comment] 2023-10-28 02:13
Not sure about this. With a bounded size it's true that the memory leak is bounded, but it's still true that you can leak a reference to a (potentially big) object this way.

**Comment by mrcljx** [comment] 2024-06-06 07:01
JFYI , the mentions on this issue play out as a drama in three acts:

1. Bugbear reported B019
2. Seemed like a false positive ("transient memory leak seems fine") and was `noqa`d.
3. Actually was a true positive ("transient memory leak is actually problematic") and was fixed.

Seeing the `noqa` in code helped finding the root cause quickly.

+1 on closing this issue.

**Closed** 2024-06-06 22:34 UTC
